### ISSUE TITLE
STMPAuthenticationEmail when sending email

### ISSUE THREAD

**Issue by sangshuduo** [huggingface/knockknock#83]
and how to reset the password in keyrings, then I can try another one

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/knockknock", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/knockknock/__main__.py", line 207, in main
    sender_func(**args)(run_func)()
  File "/opt/homebrew/lib/python3.12/site-packages/knockknock/email_sender.py", line 53, in wrapper_sender
    yag_sender.send(current_recipient, 'Training has started 🎬', contents)
  File "/opt/homebrew/lib/python3.12/site-packages/yagmail/sender.py", line 156, in send
    self.login()
  File "/opt/homebrew/lib/python3.12/site-packages/yagmail/sender.py", line 210, in login
    self._login(self.credentials)
  File "/opt/homebrew/lib/python3.12/site-packages/yagmail/sender.py", line 229, in _login
    self.smtp.login(self.user, password)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 750, in login
    raise last_exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 6a1803df08f44-6ae4b417a00sm31586036d6.107 - gsmtp')
```

**Comment by deecodess** [comment]
Hey!
Is this resolved now?
Are you using the correct app password?
